[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/HongB1/2022-KHU-Bioinformatics-lab/blob/master/code/C5_Numpy_HW_2.ipynb)

In [2]:
# Indexing and Slicing Vector ndarrays
# ndarray a에 대해 인덱싱 및 슬라이싱을 자유롭게 해보세요 => 5개 해보세요.
import numpy as np

a = np.arange(10)

In [3]:
# Indexing and Slicing Matrix ndarrays 
# Matrix 슬라이싱을 하는 방법은 다음과 같이 두가지 방법으로 할 수 있습니다.
a = np.arange(9).reshape((3, -1))
print(f'{a[0]} => {a[0][0]}, {a[0][1]}, {a[0][2]}')
print(f'{a[1]} => {a[1][0]}, {a[1][1]}, {a[1][2]}')
print(f'{a[2]} => {a[2][0]}, {a[2][1]}, {a[2][2]}')
print(a[0, 0], a[0, 1], a[0, 2], sep=' - ') 
print(a[1, 0], a[1, 1], a[1, 2], sep=' - ') 
print(a[2, 0], a[2, 1], a[2, 2], sep=' - ')

[0 1 2] => 0, 1, 2
[3 4 5] => 3, 4, 5
[6 7 8] => 6, 7, 8
0 - 1 - 2
3 - 4 - 5
6 - 7 - 8


In [4]:
# Matrix ndarray를 생성한 후, (총 3가지를 출력하세요.) 
# 1. ndarray 출력
# 2. size, shape, dimension 출력
# 3. 위의 예시처럼 두 가지 방법으로 자유롭게 Matrix를 인덱싱 해보세요. => 각각 2개씩 총 4개

In [5]:
# 위에서 생성한 Matrix ndarray를 자유롭게 슬라이싱해보세요.

## Indexing Vector with various int ndarrays
### 1. Indexing Vector with vector int ndarrays 
### 2. Indexing Vector with matrix int ndarrays
### 3. Indexing Vector with tensor int ndarrays

In [16]:
# Indexing Vector with vector int ndarrays 
# 1. a는 Vector ndarray
a = np.random.randint(0, 20, size=(10, ))
print(f'ndarray: \n{a}\n')

# 2. 인덱싱 객체(indices)를 Vector로 생성
vector_indices = np.array([0, 3, 4]) # a를 인덱싱하기 위해 인덱싱할 숫자로 이뤄진 ndarray 객체(indices) 생성

# 3. a에 대해 인덱싱 출력
print('by vector_indices: ', a[vector_indices], '\n')

# 4. a에 대해 인덱싱한 것 shape 출력
print(a[vector_indices].shape)

ndarray: 
[ 9  2 13 10 12 15 10 12  5 17]

by vector_indices:  [ 9 10 12] 

(3,)


In [17]:
# Indexing Vector with matrix int ndarrays 
# 1. a는 그대로
a = np.random.randint(0, 20, size=(10, ))
print(f'ndarray: \n{a}\n')

# 2. 이번엔 인덱싱 객체(indices)를 Matrix로 생성

# 3. a에 대해 인덱싱 출력

# 4. a에 대해 인덱싱한 것 shape 출력


ndarray: 
[ 7 10 11  6 15  7 13 13 11 18]



In [18]:
# Indexing Vector with tensor int ndarrays 
# 1. a는 그대로
a = np.random.randint(0, 20, size=(10, ))
print(f'ndarray: \n{a}\n')

# 2. 이번엔 인덱싱 객체(indices)를 Tensor로 생성

# 3. a에 대해 인덱싱 출력

# 4. a에 대해 인덱싱한 것 shape 출력


ndarray: 
[15  0 12 10  3 13 10  1  9 13]



## Indexing Matrix with various int ndarrays
### 1. Indexing Matrix with vector int ndarrays 
### 2. Indexing Matrix with matrix int ndarrays
### 3. Indexing Matrix with tensor int ndarrays

In [20]:
# Indexing Matrix with vector int ndarrays 
# 예시를 보여주기 위해 적어놨는데, 지우고 다른 케이스에 대해 새로 만들어서 해보세요.
## 1. Matrix a 생성
a = np.arange(12).reshape((3, 4)) 
print(f"ndarray: \n{a}\n")

## 2. matrix형태의 인덱싱 객체(indices) 생성
indices = np.array([0, 2])  # shape이 (2,) 인 벡터인 것
print(f"indices: \n{indices}\n")

# 3. a에 대해 인덱싱 출력
print(f"a[indices]: \n{a[indices]}") # 2짜리 안에 len=4인 vector가 2개 들어가는 것임

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

indices: 
[0 2]

a[indices]: 
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [21]:
# Indexing Matrix with matrix int ndarrays 
# 예시를 보여주기 위해 적어놨는데, 지우고 다른 케이스에 대해 새로 만들어서 해보세요.
## 1. Matrix a 생성
a = np.arange(12).reshape((3, 4)) 
print(f"ndarray: \n{a}\n")

## 2. matrix형태의 인덱싱 객체(indices) 생성
indices = np.random.randint(0, 3, size=(2, 3))
print(f"indices: \n{indices}\n")

# 3. a에 대해 인덱싱 출력
print(f"a[indices]: \n{a[indices]}") # 2짜리 안에 len=4인 vector가 2개 들어가는 것임

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

indices: 
[[0 1 0]
 [1 0 2]]

a[indices]: 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 0  1  2  3]
  [ 8  9 10 11]]]


In [22]:
# Indexing Matrix with tensor int ndarrays 
# 예시를 보여주기 위해 적어놨는데, 지우고 다른 케이스에 대해 새로 만들어서 해보세요.
## 1. Matrix a 생성
a = np.arange(12).reshape((3, 4)) 
print(f"ndarray: \n{a}\n")

## 2. tensor 형태의 인덱싱 객체(indices) 생성
indices = np.random.randint(0, 3, size=(2, 2, 4))
print(f"indices: \n{indices}\n")

# 3. a에 대해 인덱싱 출력
print(f"a[indices]: \n{a[indices]}") # 2짜리 안에 len=4인 vector가 2개 들어가는 것임

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

indices: 
[[[1 0 1 1]
  [0 2 1 1]]

 [[2 2 2 2]
  [2 2 2 0]]]

a[indices]: 
[[[[ 4  5  6  7]
   [ 0  1  2  3]
   [ 4  5  6  7]
   [ 4  5  6  7]]

  [[ 0  1  2  3]
   [ 8  9 10 11]
   [ 4  5  6  7]
   [ 4  5  6  7]]]


 [[[ 8  9 10 11]
   [ 8  9 10 11]
   [ 8  9 10 11]
   [ 8  9 10 11]]

  [[ 8  9 10 11]
   [ 8  9 10 11]
   [ 8  9 10 11]
   [ 0  1  2  3]]]]


In [24]:
"""
Indexing Tensor with vector int ndarray
"""
# 예시를 보여주기 위해 적어놨는데, 지우고 다른 케이스에 대해 새로 만들어서 해보세요.

## 1. Tensor a 생성
a = np.arange(36).reshape((3, 3, 4)) 
print(f"ndarray: \n{a}\n")

## 2. matrix형태의 인덱싱 객체(indices) 생성
indices = np.array([0, 2])  # shape이 (2,) 인 벡터인 것
print(f"indices: \n{indices}\n")

# 3. a에 대해 인덱싱 출력
print(f"a[indices]: \n{a[indices]}") # 2짜리 안에 len=4인 vector가 2개 들어가는 것임

ndarray: 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]

indices: 
[0 2]

a[indices]: 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


# Indexing with bool ndarrays

In [26]:
"""
ndarray 객체를 생성한 후, Boolean값으로 이뤄진 ndarray객체를 만들어 인덱싱해보세요.
"""
# 예시를 보여주기 위해 적어놨는데, 지우고 다른 케이스에 대해 새로 만들어서 해보세요.

# 1. ndarray 객체 생성
a = np.arange(5) 
print(f"ndarray: \n{a}")

# 2. 인덱싱하기 위한 bool ndarrays(indices) 생성
b_indices = np.array([True, False, True, False, True])
print(f"b_indices: \n{b_indices}\n")

# 3. indices를 이용하여 a를 인덱싱
print(f"a[b_indices]: \n{a[b_indices]}")

ndarray: 
[0 1 2 3 4]
b_indices: 
[ True False  True False  True]

a[b_indices]: 
[0 2 4]


In [27]:
"""
ndarray 객체를 생성한 후, 
3으로 나눈 나머지가 0인 값만 True로 반환해주는 Boolean값으로 이뤄진 ndarray객체를 만들어 인덱싱해보세요.
"""
# 예시를 보여주기 위해 적어놨는데, 지우고 다른 케이스에 대해 새로 만들어서 해보세요.

# 1. ndarray 객체 생성
a = np.random.randint(0, 20, (10, )) 
print(f"ndarray: \n{a}")

# 2. 3으로 나눈 나머지가 0인 값만 True로 반환해주는 ndarray 객체 생성
b_indices = (a % 2 == 0) # 2로 나눈 나머지가 0인 조건으로 예시를 들어놓은 것입니다. 지우고 제시한 조건에 맞게 다시 작성하세요.
print(f"b_indices: \n{b_indices}\n")

# 3. 2번에서 생성한 ndarray 객체로 a 인덱싱
print(f"a[b_indices]: \n{a[b_indices]}")


ndarray: 
[ 1 15 12 14  9  8 13  5 13  1]
b_indices: 
[False False  True  True False  True False False False False]

a[b_indices]: 
[12 14  8]


array([12, 14,  8])

In [28]:
"""
np.nonzero()를 사용하여 0이 아닌 값만 인덱싱하기
"""
# 예시를 보여주기 위해 적어놨는데, 지우고 다른 케이스에 대해 새로 만들어서 해보세요.
a = np.random.randint(-2, 1, size=(5, 5))

a_nonzero = a[np.nonzero(a)]
print(a)
print(a_nonzero)


[[ 0 -1 -2 -1 -1]
 [ 0  0  0 -1  0]
 [-2 -1 -2 -2  0]
 [-1  0 -2 -2 -2]
 [-1  0 -1  0  0]]
[-1 -2 -1 -1 -1 -2 -1 -2 -2 -1 -2 -2 -2 -1 -1]


In [32]:
"""
np.where()를 사용하여 괄호 안에 조건을 설정하여, 해당 조건을 만족하는(=True) 값만 인덱싱해보세요.
"""
# 예시를 보여주기 위해 적어놨는데, 지우고 다른 케이스에 대해 새로 만들어서 해보세요.
a = np.random.randint(-3, 7, size=(2, 3, 5))
a_where = a[np.where(a%3==0)]
print(a)
print(a_where)

[[[ 1  3  5  4  4]
  [-2  1  0  2  3]
  [ 3  0  4  1  5]]

 [[ 5  1 -2  6  0]
  [ 6  2  1  0 -1]
  [-2  3 -2  4  5]]]
[3 0 3 3 0 6 0 6 0 3]


# Axis 사용하기

In [36]:
"""
np.sum & ndarray.sum
of Matrix with axis Argument
ndarray 객체를 생성한 후, 다양한 axis를 기준으로 sum을 사용해보세요.
"""
# 예시를 보여주기 위해 적어놨는데, 지우고 다른 케이스에 대해 새로 만들어서 해보세요.

a = np.arange(16).reshape((2, 2, -1))
sum_axis0 = a.sum(axis=0)
sum_axis1 = a.sum(axis=1)
sum_axis2 = a.sum(axis=2)

print("ndarray: {}\n{}\n".format(a.shape, a)) 
print("ndarray.sum(axis=0): {}\n{}\n".format(sum_axis0.shape, sum_axis0))
print("ndarray.sum(axis=1): {}\n{}\n".format(sum_axis1.shape, sum_axis1))
print("ndarray.sum(axis=2): {}\n{}\n".format(sum_axis2.shape, sum_axis2))

ndarray: (2, 2, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

ndarray.sum(axis=0): (2, 4)
[[ 8 10 12 14]
 [16 18 20 22]]

ndarray.sum(axis=1): (2, 4)
[[ 4  6  8 10]
 [20 22 24 26]]

ndarray.sum(axis=2): (2, 2)
[[ 6 22]
 [38 54]]



In [38]:
"""
np.sum & ndarray.sum
of Matrix with axis Argument
ndarray 객체를 생성한 후, 다양한 axis를 기준으로 sum을 사용해보세요.
"""
# 예시를 보여주기 위해 적어놨는데, 지우고 다른 케이스에 대해 새로 만들어서 해보세요.

a = np.arange(16).reshape((2, 2, -1))
mean_axis0 = a.mean(axis=0)
mean_axis1 = a.mean(axis=1)
mean_axis2 = a.mean(axis=2)

print("ndarray: {}\n{}\n".format(a.shape, a)) 
print("ndarray.mean(axis=0): {}\n{}\n".format(mean_axis0.shape, mean_axis0))
print("ndarray.mean(axis=1): {}\n{}\n".format(mean_axis1.shape, mean_axis1))
print("ndarray.mean(axis=2): {}\n{}\n".format(mean_axis2.shape, mean_axis2))

ndarray: (2, 2, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

ndarray.mean(axis=0): (2, 4)
[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

ndarray.mean(axis=1): (2, 4)
[[ 2.  3.  4.  5.]
 [10. 11. 12. 13.]]

ndarray.mean(axis=2): (2, 2)
[[ 1.5  5.5]
 [ 9.5 13.5]]



In [42]:
""" . 
1. ndarray 객체 생성
2. vstack으로 쌓아보기
3. hstack으로 쌓아보기
4. 2번과 같은 결과가 나오게 np.concatenate으로 쌓아보기(axis이용)
5. 3번과 같은 결과가 나오게 np.concatenate으로 쌓아보기(axis이용)
"""
# 예시를 보여주기 위해 적어놨는데, 지우고 다른 케이스에 대해 새로 만들어서 해보세요.
# 1
a = np.random.randint(0, 10, (1, 3)) 
b = np.random.randint(0, 10, (1, 3))

print(f"a: {a.shape}\n{a}") 
print(f"b: {b.shape}\n{b}\n")

# 2
vstack = np.vstack((a, b))
print(f"vstack: {vstack.shape}\n{vstack}") 

# 3
hstack = np.hstack((a, b))
print(f"hstack: {hstack.shape}\n{hstack}\n")

# 4
concat0 = np.concatenate([a, b], axis=0)
print(concat0)

# 5
concat1 = np.concatenate([a, b], axis=1)
print(concat1)

a: (1, 3)
[[3 5 9]]
b: (1, 3)
[[9 5 3]]

vstack: (2, 3)
[[3 5 9]
 [9 5 3]]
hstack: (1, 6)
[[3 5 9 9 5 3]]

[[3 5 9]
 [9 5 3]]
[[3 5 9 9 5 3]]


In [44]:
"""
다음과 같이 에러가 나서 a, b를 horizontal 방향으로 쌓아주기 위해 b의 shape을 바꾸고자 합니다.
1. 현재 b는 row vector인데 reshape을 이용해서 column vector로 바꿔준 후 
2. a와 b를 hstack을 해보세요.
"""

a = np.random.randint(0, 10, (3, 4)) 
b = np.random.randint(0, 10, (3,))
hstack = np.hstack([a, b]) 
print(f"hstack: {hstack.shape}\n{hstack}")

# 1. b의 shape 바꾸기


# 2. a와 shape이 바뀐 b에 대하여 hsatck하기

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)