# Section 1. N차원 배열 생성
- 1차원, 2차원 배열을 생성하고 

In [2]:
import numpy as np
import sys
sys.path


# 1차원 배열
arr1 = np.array([1,2,3])
print(arr1)

# 2차원 배열
arr2 = np.array([[1,2,3],
      [4,5,6]])
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [4]:
print(type([1,2,3]))
print(type(arr1))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
tpl = (4,5,6)
arr = np.array(tpl)
print(arr)

[4 5 6]


In [6]:
lst = [1,2,3]
arr = np.array(lst)
print(arr)

[1 2 3]


In [7]:
lst2 = [[1,2,3], [4,5,6]]
arr2 = np.array(lst2)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [11]:
# shape
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3], [4,5,6]])

print(arr1.shape)
print(arr2.shape)

# ndim(차원 확인)
print(arr1.ndim, arr2.ndim)

# size
print(arr1.size, arr2.size)

(3,)
(2, 3)
1 2
3 6
